### PR TITLE
Add Missing Event Class Fields

### PR DESCRIPTION
**Pull request by Cedric-Boucher**
For issue #42 

Need to add:

- [x] event description 
- [x] event start date 
- [x]  event end date 
- [x] event registration start date
- [x] event registration end date
- [x] store whether geolocation sharing is required to sign up for event

then:
- [x] update UML

### CODE REVIEW

**Comment by Cedric-Boucher** [comment]
@aurbeez for this note you wrote in the issue:

> possibly the facility's address so that can be displayed on event details page??? (currently it doesnt tell you anything about where the event is happening)

would it be possible to send the Facility and Event to whatever fragment needs it? that's probably easier / better (?) than adding it to the Event in some way

**Comment by aurbeez** [comment]
> @aurbeez for this note you wrote in the issue:
> 
> > possibly the facility's address so that can be displayed on event details page??? (currently it doesnt tell you anything about where the event is happening)
> 
> would it be possible to send the Facility and Event to whatever fragment needs it? that's probably easier / better (?) than adding it to the Event in some way

that could work when a user is viewing their own event (i.e., when they're managing their event), however, I'm not sure how we can get the event address when scanning the qr code of another person's event (since the database is populating the event page with whatever is in the database for the eventpath given in the qr code). We wouldn't be able to access the facility object associated with the event from the eventpath unless we open the facility document (just to access one field) as well when fetching the event in the data. Do you think there's another way to get access to the address field of a facility of another user's event?

**Comment by Cedric-Boucher** [comment]
> > @aurbeez for this note you wrote in the issue:
> > > possibly the facility's address so that can be displayed on event details page??? (currently it doesnt tell you anything about where the event is happening)
> > 
> > 
> > would it be possible to send the Facility and Event to whatever fragment needs it? that's probably easier / better (?) than adding it to the Event in some way
> 
> that could work when a user is viewing their own event (i.e., when they're managing their event), however, I'm not sure how we can get the event address when scanning the qr code of another person's event (since the database is populating the event page with whatever is in the database for the eventpath given in the qr code). We wouldn't be able to access the facility object associated with the event from the eventpath unless we open the facility document (just to access one field) as well when fetching the event in the data. Do you think there's another way to get access to the address field of a facility of another user's event?

@aurbeez what if the DatabaseManager gets the parent document as well when it gets the Event from a QR Code, and returns the Facility as well?

**Comment by aurbeez** [comment]
> > > @aurbeez for this note you wrote in the issue:
> > > > possibly the facility's address so that can be displayed on event details page??? (currently it doesnt tell you anything about where the event is happening)
> > > 
> > > 
> > > would it be possible to send the Facility and Event to whatever fragment needs it? that's probably easier / better (?) than adding it to the Event in some way
> > 
> > 
> > that could work when a user is viewing their own event (i.e., when they're managing their event), however, I'm not sure how we can get the event address when scanning the qr code of another person's event (since the database is populating the event page with whatever is in the database for the eventpath given in the qr code). We wouldn't be able to access the facility object associated with the event from the eventpath unless we open the facility document (just to access one field) as well when fetching the event in the data. Do you think there's another way to get access to the address field of a facility of another user's event?
> 
> @aurbeez what if the DatabaseManager gets the parent document as well when it gets the Event from a QR Code, and returns the Facility as well?

that could work. it might be a bit unnecessary to fetch a facility object just for the address but if that way seems the most reasonable, we can implement it. for now, we can leave the address field task out of this PR

**Review by Ociliv1 — APPROVED** [review]

**Review by Ociliv1 — APPROVED** [review]

**Review by ichandel — APPROVED** [review]

**Pull request merged**
