### PR TITLE
Create base classes

### PR DESCRIPTION
**Pull request by Cedric-Boucher**

### CODE REVIEW

**Comment by Cedric-Boucher** [comment]
All of the base classes from the UML diagram (as of now) have been created and all methods exist. Some methods have not yet been implemented, and database functionality has also not yet been implemented.

I have created two new issues for the remaining tasks with base classes: #51 and #52

**Comment by Cedric-Boucher** [comment]
I still need to write some unit tests for the functionality that is implemented so far

**Comment by Cedric-Boucher** [comment]
only Event unit tests are left to make, but I'm not sure it's even possible to test it with JUnit since:
1. Event *requires* an event poster, which is a Bitmap
1. Bitmaps cannot be created when testing with JUnit as they only exist in Android, and "are not mocked" for testing in pure Java

**Comment by Cedric-Boucher** [comment]
I mocked event to remove the event poster requirement for testing Facility (so I could create an event with null event poster)
I might be able to do the same for event testing

**Comment by Cedric-Boucher** [comment]
ok I should be able to write tests for Event by using EventMock instead (which just overwrites the setEventPoster method to remove the requirement that the poster must not be null

**Review by aurbeez — APPROVED** [review]

**Review by Ociliv1 — APPROVED** [review]

**Pull request merged**
