### PR TITLE
Connect app to firestore database

### PR DESCRIPTION
**Pull request by Cedric-Boucher**

### CODE REVIEW

**Comment by Cedric-Boucher** [comment]
well that's something
looks like we can't have test cases that use the database because Github actions won't be able to run them (we don't want to put our database key publicly in the repository

**Comment by aurbeez** [comment]
some notes:
- need to test manually with these new changes
- changes to some class arguments so unit tests should be updated if we are following this format (causing errors)
- anything in the classes that stores other objects (i..e, facility that has array of events) is structured as subcollections 
(so facility has subcollection of events) instead of keeping an array of events in the database bc i thought it would be redundant
to store both that array and the events as a subcollection. if you dont like this implementation, feel free to suggest something diff
-are we supposed to be storing the whole qr code object in the event database or just the text?
- left drawEntrants method in entrantPool and sendNotification method in NotificationSender with no implementation as it is not part of our halfway checkpoint user stories

**Comment by Cedric-Boucher** [comment]
@aurbeez to answer your question about the QR codes. QR codes are deterministically generated based on a string, so we only need to store the string/text for the QR code in the database, not the actual image

**Comment by Cedric-Boucher** [comment]
all unit tests have been fixed to the point that they can now be run. but build fails because firebase stuff is not mocked

**Comment by Cedric-Boucher** [comment]
the fake google-services.json file bypasses that build error in GitHub Actions. neat

**Comment by Cedric-Boucher** [comment]
the only remaining reason why unit tests don't pass, as far as I'm aware, is that the base classes try to update the database using DatabaseManager. DatabaseManager should be mocked using Mockito for unit tests so that they can pass

**Comment by Cedric-Boucher** [comment]
I removed DatabaseManager usage from all base classes, completely. This means that it is the responsibility of code that uses the base classes to use the DatabaseManager to update the database

**Comment by Cedric-Boucher** [comment]
there is also still a FIXME note in DatabaseManager. This FIXME note is because null entrants are being returned when getting EntrantStatuses from the database. The reason for returning null entrants is that if I use the DatabaseManager to get the actual entrant (User object), there is a possibility of infinite recursion in the DatabaseManager methods. I'm not sure how to fix this, so I return null for now

**Review by aurbeez — APPROVED** [review]
Did not get to do a super detailed review but it looks good to me from my glance. I'm also not sure what to do about the entrant user FIXME

**Review by alianish11 — DISMISSED** [review]

**Review by Cedric-Boucher — COMMENTED** [review]
I've reviewed all of the changes in this PR and fixed any weird things I had initially missed. should be good now

**Review by aurbeez — DISMISSED** [review]

**Review by Cedric-Boucher — COMMENTED** [review]
I have reviewed all of the changes in this PR just now.

Note that there are a few FIXME notes and some commented code for now, since images cannot be uploaded to the database yet. I will make a new branch to fix that issue.

**Review by aurbeez — APPROVED** [review]

**Review by ichandel — APPROVED** [review]
LOOKS GOOD :THUMBS UP:

**Pull request merged**
