### PR TITLE
Us 03.04.01

### PR DESCRIPTION
**Pull request by Ociliv1**

### CODE REVIEW

**Review by ichandel — DISMISSED** [review]
incredible work!

**Comment by Cedric-Boucher** [comment]
also the build fails

**Review by aurbeez — DISMISSED** [review]
what cedric said but looks good

**Comment by Cedric-Boucher** [comment]
@Ociliv1 look into the methods I have marked as deprecated in the merge commit. I will make the DatabaseManager methods you need

**Pull request merged**
