### PR TITLE
US 03.05.01

### PR DESCRIPTION
**Pull request by Cedric-Boucher**

### CODE REVIEW

**Comment by Ociliv1** [comment]
checks failed due to database

**Comment by Cedric-Boucher** [comment]
looks like there's build errors in GitHub actions due to firebase code

**Comment by Cedric-Boucher** [comment]
note that the deleteUser method in the User class on this branch will have to be manually merged properly with the database branch once that's done

**Comment by Cedric-Boucher** [comment]
build no longer fails but a bunch of tests don't pass

**Comment by Cedric-Boucher** [comment]
@Ociliv1 look into the methods I have marked as deprecated in the merge commit. The method you need already exists in DatabaseManager. Convert your code to use that instead and delete your deprecated method once it is no longer being used (this is necessary to get tests to pass anyway btw)

**Pull request merged**
